# Kitty config - Monokai Theme

# The basic colors
foreground              #F8F8F2
background              #10001b 
selection_foreground    #F8F8F2
selection_background    #49483E

# Cursor colors
cursor                  #F8F8F2
cursor_text_color       #272822

# URL underline color when hovering with mouse
url_color               #F8F8F2

# Kitty window border colors
active_border_color     #F92672
inactive_border_color   #75715E
bell_border_color       #F92672

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #F8F8F2
active_tab_background   #75715E
inactive_tab_foreground #F8F8F2
inactive_tab_background #272822
tab_bar_background      #272822

# Colors for marks (marked text in the terminal)
mark1_foreground #F8F8F2
mark1_background #F92672
mark2_foreground #F8F8F2
mark2_background #A6E22E
mark3_foreground #F8F8F2
mark3_background #E6DB74

# The 16 terminal colors

# black
color0 #272822
color8 #75715E

# red
color1 #F92672
color9 #F92672

# green
color2 #A6E22E
color10 #A6E22E

# yellow
color3 #F4BF75
color11 #F4BF75

# blue
color4 #66D9EF
color12 #66D9EF

# magenta
color5 #F8F8F2
color13 #F8F8F2

# cyan
color6 #A1EFE4
color14 #A1EFE4

# white
color7 #F8F8F2
color15 #F8F8F2
